apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-name
spec:
  capacity:
    storage: ${EFS_SERVER_VOLUME}
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${EFS_SERVER}
    path: "/"
